---
apiVersion: v1
kind: Service
metadata:
  name: data-stream-delivery-service
  labels:
    app: data-stream-delivery
spec:
  ports:
    - name: http
      port: 7778
      targetPort: 7778
  type: LoadBalancer
  selector:
    app: data-stream-delivery